### ISSUE TITLE
按键选择接收机时，必然会初始化dsmx对频

### ISSUE THREAD

**Issue by wenzhicode** [BETAFPV/LiteSilverware#3]
需要在飞控中调整代码顺序。

**Comment by SchizoDuckie** [comment]
English translation:
*When the button is selected to select the receiver, it will inevitably initialize the dsmx pair frequency #3*
Need to adjust the code order in the flight control.

--

Because of the existing dsm receiver, the time to power up waiting for the frequency pulse is limited.  Waiting for the button is longer than the time the receiver waits for the frequency signal.  There is currently no more convenient solution to this conflict.
